---
spring:
  application:
    name: ordersworkflow
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
orderprocessingservice-url: http://orderprocessing-service/
temporal:
  taskQueue: orders-tasks
  target: orders-dev.sdvdw.tmprl.cloud:7233
  ns: orders-dev.sdvdw
  cert: /usr/local/bin/ca.pem
  key: /usr/local/bin/ca.key
logging:
  level:
    io.temporal: INFO

