---
spring.application.name: ordersworkflow
orderprocessingservice-url: http://orderprocessing-service/
temporal:
  taskQueue: orders-tasks
  target: orders-dev.ydusq.tmprl.cloud:7233
  ns: orders-dev.ydusq
  cert: /usr/local/bin/ca.pem
  key: /usr/local/bin/ca.key
logging:
  level:
    io.temporal: DEBUG