apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: ordersworkflow-image
  namespace: default
spec:
  tag: stwomack/ordersworkflow
  serviceAccountName: main-builder-service-account
  builder:
    name: main-builder
    kind: Builder
  source:
    git:
      url: https://github.com/stwomack/ordersworkflow
      revision: main